print('2.  - Installing Libraries')

cloud_repo = 'https://cloud.r-project.org/'

if (!require(MASS)) install.packages('MASS', repos = cloud_repo)
if (!require(class)) install.packages('class', repos = cloud_repo)
if (!require(caret)) install.packages('caret', repos = cloud_repo)
if (!require(glmnet)) install.packages('glmnet', repos = cloud_repo)
if (!require(tree)) install.packages('tree', repos = cloud_repo)
if (!require(dplyr)) install.packages('dplyr', repos = cloud_repo, verbose=F)
if (!require(ggplot2)) install.packages('ggplot2', repos = cloud_repo)
if (!require(RColorBrewer)) install.packages('RColorBrewer', repos = cloud_repo)
if (!require(gridExtra)) install.packages('gridExtra', repos = cloud_repo, verbose=F)
if (!require(foreach)) install.packages('foreach', repos = cloud_repo)
if (!require(doParallel)) install.packages('doParallel', repos = cloud_repo)
if (!require(readr)) install.packages('readr', repos = cloud_repo)
if (!require(bigstatsr)) install.packages('bigstatsr', repos = cloud_repo)
if (!require(rpart)) install.packages('rpart', repos = cloud_repo)
if (!require(stats)) install.packages('stats', repos = cloud_repo) 
if (!require(ggpubr)) install.packages('ggpubr', repos = cloud_repo) 
if (!require(xtable)) install.packages('xtable', repos = cloud_repo)
if (!require(data.table)) install.packages('data.table', repos = cloud_repo, verbose=F)
if (!require(reshape2)) install.packages('reshape2', repos = cloud_repo, verbose=F)


library(MASS)   # wasn't sure if I needed to call here and also in other scripts
library(class)  # so I did both!
library(caret)
library(glmnet)
library(tree)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(foreach)
library(doParallel)
library(readr)
library(bigstatsr)
library(rpart)
library(stats)
library(ggpubr)
library(xtable)
library(data.table)
library(reshape2)

